#! /bin/sh

# Extracts the cover art from the given mp3 file. Uses ffmpeg.

set -e

if [ $# -lt 1 ]; then
  echo "USAGE: id3-image-extract <mp3-filename> [<image-filename>]"
  exit 1
fi

music_file=${1?}
image_file=${2:-${music_file%.*}.jpg}

ffmpeg -i "$music_file" "$image_file"
