#! /bin/sh

set -e

if [[ $# -lt 1 ]]; then
  echo "USAGE: new-script <scriptname>"
  exit 1
fi

name=$1

if [ -f "$HOME/projects/scripts/$name" ]; then
  echo "File ~/projects/scripts/$name already exists"
  exit 1
fi

if [ -f "$HOME/bin/$name" ]; then
  echo "File ~/bin/$name already exists"
  exit 1
fi

{
  echo "#! /bin/sh";
  echo "";
  echo "set -e";
  echo "";
  echo "echo OK";
} >> "$HOME/projects/scripts/$name"

chmod +x "$HOME/projects/scripts/$name"
ln -s "$HOME/projects/scripts/$name" "$HOME/bin/$name"
