#! /usr/bin/env ruby

# Changes the current directory to a "project", where a "project" could be:
#   - Defined in .vimproj for the Proj.vim plugin
#   - A directory under ~/projects/
#
# If given several projects, will attempt to open them in new terminal windows
# (using urxvt).
#
# Completion (copy to .zshrc):
#
#   _proj_completion() {
#     reply=(`{ sed -n -e '/^\[/p' -e '/^\s*$/d' ~/.vimproj | sed -e 's/\[//' -e 's/]//'; /bin/ls ~/projects } | cat | sort | uniq`)
#   }
#   compctl -K _proj_completion vimproj
#

require 'inifile'
require 'fileutils'

if ARGV.length < 1
  puts "USAGE: proj <project-name>"
  exit 1
end

project, *other_projects = ARGV

other_projects.each do |project|
  system "urxvt -T 'proj #{project}' -e zsh -i -c 'proj #{project}' & disown"
end

VIMPROJ = IniFile.load("#{ENV['HOME']}/.vimproj")

if VIMPROJ[project] && VIMPROJ[project]["path"]
  path = VIMPROJ[project]["path"]
elsif File.directory?("#{ENV['HOME']}/projects/#{project}")
  path = "#{ENV['HOME']}/projects/#{project}"
end

if path
  FileUtils.cd path
  Kernel.exec ENV['SHELL']
else
  puts "Project ${project} not found in .vimproj or under ~/projects"
end
