#! /bin/sh

# Takes the given file and moves it to the current directory. Leaves a symlink in
# its place that points to the new location.

set -e

path=$1
target_dir=${2:-$(pwd)}

if [[ -z "$path" ]]; then
  echo "USAGE: symlinkize <real-path>"
  echo
  echo "  Will move the file to $(pwd)/"
  echo
  exit 1
fi

filename=$(basename "$path")

mv "$path" "$target_dir/$filename"
ln -s "$target_dir/$filename" "$path"
