#! /usr/bin/env bash

# Opens a "project" with Vim, where a "project" could be:
#   - Defined in .vimproj for the Proj.vim plugin
#   - A directory under ~/projects/
#   - A directory under ~/.vim/bundle/
#
# If given several projects, will attempt to open them in new terminal windows
# (using urxvt).
#
# Completion (copy to .zshrc):
#
#   _proj_completion() {
#     reply=(`{ sed -n -e '/^\[/p' -e '/^\s*$/d' ~/.vimproj | sed -e 's/\[//' -e 's/]//'; /bin/ls ~/projects; /bin/ls ~/.vim/bundle; } | cat | sort | uniq`)
#   }
#   compctl -K _proj_completion vimproj
#

set -e

if [ $# -lt 1 ]; then
  echo "USAGE: vimproj <project-name>"
  exit 1
fi

project=$1
shift
other_projects=$*

for other_project in $other_projects; do
  urxvt -e zsh -i -c "vimproj $other_project" & disown
done

if grep "\[$project\]" ~/.vimproj > /dev/null; then
  vim +"Proj $project"
elif [ -d "$HOME/.vim/bundle/$project" ]; then
  vim $HOME/.vim/bundle/$project
elif [ -d "$HOME/projects/$project" ]; then
  vim $HOME/projects/$project
else
  echo "Project $project not found in ~/.vimproj or under ~/projects"
  exit 1
fi
